version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  commit-message:
    prefix: "actions"
  labels: [ 'github-actions' ]
  assignees:
  - "Harvester57"
  schedule:
    interval: "cron"
    cronjob: "0 7 * * *"
    timezone: "Europe/Paris"
  groups:
    actions-dependencies:
      applies-to: version-updates
      patterns:
      - "*"
