name: Linting
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
    linting:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                files: [
                      "AdditionalHardening.admx", 
                      "AdditionalDebugPolicies.admx", 
                      "AdditionalDefenderPolicies.admx", 
                      "AdditionalHardeningFromMicrosoft.admx", 
                      "AdditionalLegacyHardening.admx", 
                      "AdditionalNetworkHardening.admx", 
                      "AdditionalSystemHardening.admx"
                      ]
        container:
            image: ghcr.io/harvester57/docker-admxlint:main
            options: --user root
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
              with:
                egress-policy: audit

            -  name: Checkout
               uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
               with:
                 persist-credentials: false

            -  name: Lint ADMX files
               run: admx-lint --input_file ${{ matrix.files }}
    
    lint-powershell:
        permissions:
          security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
        name: PSScriptAnalyzer
        runs-on: ubuntu-latest
        steps:
          - name: Harden the runner (Audit all outbound calls)
            uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
            with:
              egress-policy: audit

          - name: Checkout
            uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
            with:
              persist-credentials: false
    
          - name: Run PSScriptAnalyzer
            uses: microsoft/psscriptanalyzer-action@6b2948b1944407914a58661c49941824d149734f
            with:
              # Check https://github.com/microsoft/psscriptanalyzer-action for more info about the options.
              path: .\
              recurse: true
              output: results.sarif
    
          # Upload the SARIF file generated in the previous step
          - name: Upload SARIF results file
            uses: github/codeql-action/upload-sarif@87557b9c84dde89fdd9b10e88954ac2f4248e463 # v4.36.1
            with:
              sarif_file: results.sarif
    
